version: 2
jobs: 
  build: 
    docker: 
      - 
        image: "circleci/node:latest"
    steps: 
      - checkout
      - 
        run: 
          command: "sudo npm install -g npm@latest"
          name: "Update npm"
      - 
        restore_cache: 
          key: "dependency-cache-{{ checksum \"package.json\" }}"
      - 
        run: 
          command: "npm install"
          name: "Install npm"
      -
        run: 
          command: "npm audit fix --force"
          name: "Fix npm audit"
      - 
        save_cache: 
          key: "dependency-cache-{{ checksum \"package.json\" }}"
          paths: 
            - node_modules
      
    working_directory: ~/trilnh92
  deploy: 
    docker: 
      - 
        image: "circleci/node:latest"
    steps: 
      - checkout
      - 
        restore_cache: 
          key: "dependency-cache-{{ checksum \"package.json\" }}"      
      - 
        run: 
          command: "npm install"
          name: "Install npm"
      -
        run: 
          command: "npm audit fix --force"
          name: "Fix npm audit"
      - 
        save_cache: 
          key: "dependency-cache-{{ checksum \"package.json\" }}"
          paths: 
            - node_modules
      - 
        run: 
          command: "npm run build"
          name: "Build the web application"
      - 
        run: 
          command: "npm run deploy"
          name: "Delpoy the build"
  test: 
    docker: 
      - 
        image: "circleci/node:latest"
    steps: 
      - checkout
      - 
        run: 
          command: "npm test"
          name: Test
      - 
        run: 
          command: "./node_modules/.bin/nyc report --reporter=text-lcov"
          name: "Generate code coverage"
      - 
        store_artifacts: 
          path: test-results.xml
          prefix: tests
      - 
        store_artifacts: 
          path: coverage
          prefix: coverage

workflows: 
  version: 2
  deploy-job: 
    jobs: 
      #- deploy
      # Skip test
      #- 
        #test: 
          #filters: 
            #branches: 
              #only: master
          #requires: 
            #- build
      - 
        deploy
          filters
            branches
              only: master
